use crate::handlers::agreements;
use crate::handlers::deals::{
    create_deal, execute_transition, get_deal, list_deals, submit_deal, terms, update_deal,
    validate_deal, value_distribution,
};
use crate::handlers::milestones;
use actix_web::web;

pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/deals")
            .route(web::post().to(create_deal::create_deal))
            .route(web::get().to(list_deals::list_deals)),
    )
    .service(
        web::resource("/deals/{id}")
            .route(web::get().to(get_deal::get_deal))
            .route(web::put().to(update_deal::update_deal))
            .route(web::patch().to(update_deal::update_deal)),
    )
    .service(web::resource("/deals/{id}/submit").route(web::post().to(submit_deal::submit_deal)))
    .service(
        web::resource("/deals/{id}/transitions")
            .route(web::post().to(execute_transition::execute_transition)),
    )
    .service(
        web::resource("/deals/{id}/terms")
            .route(web::post().to(terms::propose_term))
            .route(web::get().to(terms::list_terms)),
    )
    .service(
        web::resource("/deals/{id}/terms/{term_id}/counter")
            .route(web::post().to(terms::counter_term)),
    )
    .service(
        web::resource("/deals/{id}/terms/{term_id}/accept")
            .route(web::post().to(terms::accept_term)),
    )
    .service(
        web::resource("/deals/{id}/terms/{term_id}/reject")
            .route(web::post().to(terms::reject_term)),
    )
    .service(
        web::resource("/deals/{id}/terms/{term_id}/withdraw")
            .route(web::post().to(terms::withdraw_term)),
    )
    .service(
        web::resource("/deals/{id}/value-distribution")
            .route(web::post().to(value_distribution::set_value_distribution))
            .route(web::get().to(value_distribution::get_value_distribution)),
    )
    .service(
        web::resource("/deals/{id}/validate").route(web::post().to(validate_deal::validate_deal)),
    )
    .service(
        web::resource("/deals/{id}/agreement")
            .route(web::get().to(agreements::get_agreement::get_agreement)),
    )
    .service(
        web::resource("/deals/{id}/agreement/sign")
            .route(web::post().to(agreements::sign_agreement::sign_agreement)),
    )
    .service(
        web::resource("/deals/{id}/milestones")
            .route(web::post().to(milestones::create_milestone))
            .route(web::get().to(milestones::list_milestones)),
    )
    .service(
        web::resource("/deals/{id}/milestones/progress")
            .route(web::get().to(milestones::get_deal_progress)),
    )
    .service(
        web::resource("/deals/{id}/milestones/{milestone_id}")
            .route(web::put().to(milestones::update_milestone))
            .route(web::patch().to(milestones::update_milestone))
            .route(web::delete().to(milestones::delete_milestone)),
    )
    .service(
        web::resource("/deals/{id}/milestones/{milestone_id}/start")
            .route(web::post().to(milestones::start_milestone)),
    )
    .service(
        web::resource("/deals/{id}/milestones/{milestone_id}/complete")
            .route(web::post().to(milestones::complete_milestone)),
    )
    .service(
        web::resource("/deals/{id}/milestones/{milestone_id}/verify")
            .route(web::post().to(milestones::verify_milestone)),
    );
}
